### ISSUE TITLE
Add loginSuccess hook to LoginPage.tsx

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/AppBase#101]
We have a hook already to override what happens after a successful login.  In addition to that we need one that doesn't override the default logic, but allows you to fire additional code.

This will be used by apps like StreamingLive to check if the church has been configured yet for this app and create a default configuration if not.

**Comment by pranavmalvawala** [comment]
Why can't we just use `loginSuccessOverride`? In my understanding, it is already being fired where we want to, all we need to do it just update to proper naming for the prop.

**Comment by jzongker** [comment]
Sometimes we need to run code **instead of** the default login success behavior, other times we need to run code **in addition to** the default behavior.

**Comment by jzongker** [comment]
This is unnecessary after all since there's just a single line of code in AppBase that isn't called when using loginSuccessOverride

`props.context.setUserName(UserHelper.currentChurch.id.toString());`

It makes more sense for apps that need custom login success code to just manually set this value rather than having a second hook.
