### ISSUE TITLE
Remove interfaces from this repo and have an induvial standalone repo

### ISSUE THREAD

**Issue by pranavmalvawala** [LiveChurchSolutions/AppBase#122]
Try and publish the repo on npm.

**Comment by jzongker** [comment]
@pranavmalvawala  I think we talked through this a month or two ago and decided it was more effort than it's worth for now.  If you agree, can you close the issue?  If not, let's discuss.

**Comment by pranavmalvawala** [comment]
True, this is just an old one. I'm closing it!
