### ISSUE TITLE
Add address to church search results

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/AppBase#137]
It's confusing when multiple churches share the same name and haven't added a logo.  There's no way to tell which is which.  Add the address/city/state/zip to the search results

**Comment by PhotoPaul** [comment]
I pushed an implementation of this. Please note that -based on what I understood you were asking- the address/city/state/zip only appears during **searching** for a church (the user needs to click on "Choose another church" and then press the Search button), and not right after a user logins. Please let me know if you want something different.
