### ISSUE TITLE
failed to remove the spaces

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/AppBase#141]
When registering a new church it failed to remove the spaces for the subdomain after a refresh and logging in again it worked.

**Comment by PhotoPaul** [comment]
Hey @mbyrdLCS ,
Can you please elaborate a little more on this?:
- What data did you enter? (I assume a church name with spaces in it, feel free to give me some fake data that produce the same issue)
- What was the expected behavior? (was it to autocomplete the subdomain without spaces, or was it something else?)

Thank you

**Comment by mbyrdLCS** [comment]
I was Signing up Osage Hills Christian Church On Lessons.Church when I noticed this issue as I just tried again and the same problem is there.

After you get the email "Welcome to Lessons.church. Your temporary password is iFSAbzaFp7N. Please visit https://lessons.church/login to login and change your password."  

You then need to login and make a church 
![Screen Shot 2022-05-17 at 6 26 33 AM](https://user-images.githubusercontent.com/65249159/168801007-37b1a913-9037-4b7f-ae3f-d1f1406af4c8.png)

You put in your church which usually has spaces it gives you this screen 

![Screen Shot 2022-05-17 at 6 27 00 AM](https://user-images.githubusercontent.com/65249159/168801635-ede76cbf-5440-4c56-8e49-3f96fbb50526.png)

Then this screen at witch it should not put spaces in where the subdomain is 
![Screen Shot 2022-05-17 at 6 27 08 AM](https://user-images.githubusercontent.com/65249159/168801696-b738b560-e476-4cc6-bd2d-1015a3286ca9.png)

If you leave spaces in there or go in and make spaces it should give you an error it just does this.

![Screen Shot 2022-05-17 at 6 28 01 AM](https://user-images.githubusercontent.com/65249159/168801847-de29c000-2b43-4972-826d-efe88ec0f1b9.png)

My guess is that people are not signing up sometimes because they don't know to make the subdomain with no spaces.
