### ISSUE TITLE
Failed login with cookie is confusing.

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/AppBase#145]
When the login with cookie fails, the user is presented with this page, which is confusing.  After a failed login attempt with a cookie, take away the "Welcome back" message and don't display any error at all.  Just prompt the user to log in.

![image](https://user-images.githubusercontent.com/1447203/169385691-7711b994-6028-4e82-a053-fa402f27bd4b.png)

**Comment by PhotoPaul** [comment]
@jzongker Please refer to my answer here: https://github.com/LiveChurchSolutions/AppBase/issues/144#issuecomment-1132677788

**Comment by jzongker** [comment]
Left a comment on #144 too, but I think for this ticket it's just a matter of a client side check for the "Welcome back" message on failure and if it's present, remove that message rather than displaying the error.
