### ISSUE TITLE
Error handling issue is still there

### ISSUE THREAD

**Issue by PhotoPaul** [LiveChurchSolutions/AppBase#147]
@jzongker, I don't think the Error logging issue is fixed.

https://github.com/LiveChurchSolutions/AppBase/blob/3d5f8f8375736dc636880b378c5b7da103bb4868/helpers/ApiHelper.ts#L132-L136

As soon as the `await response.json()` is run, instead of waiting for the Promise of `response.json()` and then throwing the exeption that would move execution back to LoginPage.tsx Line 189, the execution moves back to Line 186:
https://github.com/LiveChurchSolutions/AppBase/blob/3d5f8f8375736dc636880b378c5b7da103bb4868/pageComponents/LoginPage.tsx#L184-L191

As a result the error is never shown, the `resp` on Line 186 is `null`, and the login form freezes indefinitely...

**Comment by jzongker** [comment]
Good catch!  I had failed to await the async error handling method so postAnonymous was returning prematurely.  It's fixed now.  https://github.com/LiveChurchSolutions/AppBase/commit/f00453e6f8fe2fcb1bd106b5860db25ca6bf99aa  Odd thing is it was working while I tested it yesterday.  I guess the console.log statements I had in there for debugging was slowing it down just enough to allow resp.json() to finish before.
