### ISSUE TITLE
Material: Make switch app work in user menu

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/AppBase#153]
Link up the list of apps (Accounts App, Chums, StreamingLive, B1, Lessons.church) to the actual urls in the switch app tab of the user menu dropdown.  

I think hard code to the production url for each app unless there's an environment variable overriding.

It'd be a nice bonus if it could pass the JWT to log the user into the app automatically.  Even better if it auto picked the right church too.

**Comment by PhotoPaul** [comment]
Here is a first step:
https://github.com/LiveChurchSolutions/AppBase/commit/4c291a37b138e19b7007ab55bdd12ce763d738ce

**Comment by PhotoPaul** [comment]
And here is the second step:
https://github.com/LiveChurchSolutions/AppBase/commit/b18967de0cdb334782826d09b57d55aad059eb31
