### ISSUE TITLE
Don't require login when user clicks on profile

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/AppBase#166]
When I user clicks on profile (chums, b1, streaminglive, lessons.church) it redirects to accounts.churchapps.org.  This redirect requires the user to log in again.  Instead redirect fully logged in with the current church selected.

I believe we already accepts a ?jwt= and &returnUrl= parameters on the /login page.   We should be able to send the user to accounts.churchapps.org/login with the jwt and return url.

**Comment by PhotoPaul** [comment]
Fixed: https://github.com/LiveChurchSolutions/AppBase/compare/96a341c506c03f25527ca974cc37750c5bd94574...5798686212005029dce2b3245e12bae1b947d3b0#diff-28b17f226169dc20c79e29f19d37c997e38033102b4a3f9c25794fd1b2964145
