### ISSUE TITLE
Make re-usable help icon

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/AppBase#167]
Make a simple component along the lines of:
`<HelpIcon article="streaminglive/header-links" />`

This will be used in the top-right corner of the <InputBox> components to provide help on specific sections.
![image](https://user-images.githubusercontent.com/1447203/196552228-07889234-947d-4f17-bce9-46456839db23.png)

It should just render a simple help icon link and open the article https://support.churchapps.org/streaminglive/header-links.html in a new tab.  

Bonus points if you can figure out a way to show a preview modal of the article on mouse over.  Not necessary though.

**Comment by jzongker** [comment]
The goal is to have one of these icons in the top right corner of every input box in every app..  I believe we currently have the articles needed to do this for StreamingLive if you wan to plug those in once the component is ready.

**Comment by PhotoPaul** [comment]
@jzongker
Wouldn't it be better, instead of creating a standalone un-anchored `<HelpIcon>` component, include this in the `<InputBox>` as an optional param and then use it like this?:
```<InputBox helpArticle="streaminglive/header-links" />```

In this case, when this param is set it will render like this:

![image](https://user-images.githubusercontent.com/3471804/196889932-dfe723bf-9338-4f8d-bac1-0f750748a520.png)

**Comment by jzongker** [comment]
Yeah, I think that is better.  There may be times we want to use it on DisplayBox as well, so it may still need to be a shared component each of those call, even if it's not exposed outside of appBase.

**Comment by PhotoPaul** [comment]
I built a basic implementation reusing `<SmallButton>`: 431652bf8230adbb16152db205c56300fee5b980 & 3aa393193f4f1931678082cabab60e306a5ee59e
I also added the specific help article on the Streaming App: [12da76ec32b8732429e1e7fdf53db5e270a57d11
](https://github.com/LiveChurchSolutions/StreamingLiveApp/commit/12da76ec32b8732429e1e7fdf53db5e270a57d11)
