### ISSUE TITLE
Long Term basis - refactor all the code here in packages

### ISSUE THREAD

**Issue by pranavmalvawala** [LiveChurchSolutions/AppBase#84]
We can do a package name livechurchsolutions upload it on npm registery thereafter import the package in all apps.

**Why I came to this?**

1. I cannot use any of the components in nextjs app cause some are dependent on `react-router-dom` or other dependencies which makes no sense for next app.
2. Same with css files, if a component in appbase has its own css file then I cannot use that component cause global css can only be imported in `_app.tsx` file

**Reasons to do it**

1. Just having a package to install simplifies things, we can get rid of the whole appBase approach.
2. We can share interfaces across api and frontend apps just using 1 package
3. Will make us think in broad way when we create new components to avoid this interdependency on routing or other packages.
4. It removes the issue where sometimes we need to add dependency which we don't even use directly but appBase uses it in a file which is not related or useful to the current app in which we are using the appbase.

Eager to hear your thoughts @jzongker. @tec7z7  btw I know creating a package has an overhead but on a long term basis I think its a right way. Consider the package as an internal developer tool made for LCS projects .

**Comment by tec7z7** [comment]
I like this idea, I think it would simplify things and allow for more flexibility and options in the future.

**Comment by pranavmalvawala** [comment]
Closing this as its tabled for now!
